In [1]:
import numpy as np
import time

a = np.array([1,2,3,4])
print (a)

b = np.random.rand(1000000)
c = np.random.rand(1000000)

#current time
tic = time.time()
d = np.dot(b,c)
tac = time.time()

print("Vectorized version: " + str(1000*(tac-tic)) + " ms")

tic = time.time()
res = 0
for i in range(1000000):
    res += b[i]*c[i]
tac = time.time()

print("Non vectorized version: " + str(1000*(tac-tic)) + " ms")

[1 2 3 4]
Vectorized version: 1.3804435729980469 ms
Non vectorized version: 490.4148578643799 ms


In [7]:
#broadcasting
A = np.array([[56,0,4.4, 64.0],[1,4,56,13],[32,44,16,23]])
print(A)

cal = A.sum(axis=0)
print(cal)
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[ 56.    0.    4.4  64. ]
 [  1.    4.   56.   13. ]
 [ 32.   44.   16.   23. ]]
[  89.    48.    76.4  100. ]
[[ 62.92134831   0.           5.7591623   64.        ]
 [  1.12359551   8.33333333  73.29842932  13.        ]
 [ 35.95505618  91.66666667  20.94240838  23.        ]]


In [34]:
a = np.random.rand(5)
print(str(a.shape) + " rank 1 array") # DO NOT USE THIS FORM
print(a.T)
print(np.dot(a, a.T)/(np.linalg.norm(a)*np.linalg.norm(a.T)))

a = np.random.rand(5,1)
print(str(a.shape) + " rank 1 array") # USE THIS FORM
print(a.T)
print(a)
print(np.dot(a, a.T)/(np.linalg.norm(a)*np.linalg.norm(a.T)))

(5,) rank 1 array
[ 0.19990278  0.35838773  0.03324579  0.65891083  0.37227649]
1.0
(5, 1) rank 1 array
[[ 0.89354741  0.35512041  0.68111601  0.58646318  0.58370678]]
[[ 0.89354741]
 [ 0.35512041]
 [ 0.68111601]
 [ 0.58646318]
 [ 0.58370678]]
[[ 0.38513503  0.1530633   0.29357327  0.2527762   0.25158814]
 [ 0.1530633   0.06083158  0.11667413  0.10046024  0.09998807]
 [ 0.29357327  0.11667413  0.22377935  0.19268134  0.19177573]
 [ 0.2527762   0.10046024  0.19268134  0.16590495  0.16512519]
 [ 0.25158814  0.09998807  0.19177573  0.16512519  0.16434909]]
